# Generated by Django 3.0.6 on 2020-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_project_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_submitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_project_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_submitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='is_submitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitter',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitter',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitter',
            name='is_project_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='is_developer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='is_project_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submitter',
            name='is_submitter',
            field=models.BooleanField(default=True),
        ),
    ]
