# Generated by Django 3.0.6 on 2020-07-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='project_manager',
            new_name='pm',
        ),
    ]
