# Generated by Django 3.0.6 on 2020-07-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200719_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='pm',
            new_name='project_manager',
        ),
    ]
