# Generated by Django 3.0.6 on 2020-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_ticket_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Error', 'Error'), ('feature_request', 'Feature Request')], max_length=15, null=True),
        ),
    ]
