# Generated by Django 3.0.6 on 2020-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_phone'),
        ('Tracker', '0004_auto_20200715_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_devs',
            field=models.ManyToManyField(to='users.Developer'),
        ),
    ]
