# Generated by Django 3.0.6 on 2020-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
