# Generated by Django 3.0.6 on 2020-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_ticketcomment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
